project_id = "pkqxtalbtlbpynfjcllw"

[functions.process-pdf]
verify_jwt = true

[functions.chat-rag]
verify_jwt = true

[functions.generate-quiz]
verify_jwt = true

[functions.generate-quiz-with-pinecone]
verify_jwt = true

[functions.youtube-recommendations]
verify_jwt = true
